version: '3.8'

services:
  backend:
    depends_on:
      - mysql-db
    image: karymgharby/achat:1.0
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{"spring.datasource.url": "jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true","spring.datasource.username": "root","spring.datasource.password": null,"spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect","spring.jpa.hibernate.ddl-auto": "update"}'
    stdin_open: true
    tty: true

  mysql-db:
    image: mysql:latest
    container_name: stock-mysql
    restart: always
    environment:
      MYSQL_DATABASE: achat
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
